name: learning_app
description: "My tutorial Learning Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dots_indicator: ^4.0.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  shared_preferences: ^2.5.3
  riverpod_annotation: ^2.6.1  # ✅ Correct version that exists

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.3
  riverpod_generator: ^2.6.1   # ✅ Matching the annotation version

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/voice/