// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBxIyq12_kx11UpCI3Ljk6uLVyltXQx8',
    appId: '1:811490494943:web:2eb7483a11644393bd9c6a',
    messagingSenderId: '811490494943',
    projectId: 'learning-app-8c6e3',
    authDomain: 'learning-app-8c6e3.firebaseapp.com',
    storageBucket: 'learning-app-8c6e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIlY1-df_njDYxs9TVOQdzO1J02mn-Uw',
    appId: '1:811490494943:android:bc1bb4f4ca2c5b61bd9c6a',
    messagingSenderId: '811490494943',
    projectId: 'learning-app-8c6e3',
    storageBucket: 'learning-app-8c6e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQrdtA9hzIyWOM6pDRZtXB7udaHoGSe8',
    appId: '1:811490494943:ios:471e50c66c1c3a4dbd9c6a',
    messagingSenderId: '811490494943',
    projectId: 'learning-app-8c6e3',
    storageBucket: 'learning-app-8c6e3.firebasestorage.app',
    iosBundleId: 'com.samuel.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQrdtA9hzIyWOM6pDRZtXB7udaHoGSe8',
    appId: '1:811490494943:ios:471e50c66c1c3a4dbd9c6a',
    messagingSenderId: '811490494943',
    projectId: 'learning-app-8c6e3',
    storageBucket: 'learning-app-8c6e3.firebasestorage.app',
    iosBundleId: 'com.samuel.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArBxIyq12_kx11UpCI3Ljk6uLVyltXQx8',
    appId: '1:811490494943:web:ec0d4870ac85bf5bbd9c6a',
    messagingSenderId: '811490494943',
    projectId: 'learning-app-8c6e3',
    authDomain: 'learning-app-8c6e3.firebaseapp.com',
    storageBucket: 'learning-app-8c6e3.firebasestorage.app',
  );
}
